version: "3.9"
services:
  database:
    image: "library/postgres:latest"
#    ports:
#      - "5432:5432"
    environment:
      - POSTGRES_USER=usr
      - POSTGRES_PASSWORD=pwd
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: always
  lesson-instance-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_USERNAME=usr
      - DATABASE_PASSWORD=pwd
      - GENERAL_SESSIONQUEUEURL=host.docker.internal
    restart: always